name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
        
    - name: Enforce .NET 8 for CI
      run: echo '{"sdk":{"version":"9.0.100","rollForward":"latestFeature"}}' > global.json

    - name: Verify .NET Version
      run: dotnet --info

    - name: Restore dependencies
      run: dotnet restore ChoreBuddies.sln 

    - name: Build
      run: dotnet build ChoreBuddies.sln --no-restore --configuration Release

    - name: Test
      run: dotnet test ChoreBuddies.sln --no-build --configuration Release --verbosity normal
      
    - name: Install dotnet-format tool
      run: dotnet tool install -g dotnet-format
      
    - name: Check code formatting backend
      run: |
        # This command will fail (exit code 1) if any files are not formatted correctly.
        dotnet format ChoreBuddies.Backend/ChoreBuddies.Backend.csproj --verify-no-changes --verbosity detailed
        
    - name: Check code formatting frontend
      run: |
        # This command will fail (exit code 1) if any files are not formatted correctly.
        dotnet format ChoreBuddies.Frontend/ChoreBuddies.Frontend.csproj --verify-no-changes --verbosity detailed
